services:
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: "Europe/Zurich"
    volumes:
      - ./symfony/:/var/www/symfony/
      - ./docker/php/logs/:/symfony-logs/
    networks:
      - jaisocx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  jaisocx_http:
    build:
      context: ./docker/jaisocx-http
    volumes:
      - ./docker/jaisocx-http/conf/:/usr/lib/jaisocx-http/apps/congratulations/conf/
      - ./docker/jaisocx-http/etc/:/usr/lib/jaisocx-http/etc/
      - ./docker/jaisocx-http/logs/:/usr/lib/jaisocx-http/logs/
      - ./symfony/:/var/www/symfony/
    depends_on:
      - php
    ports:
      - 2291:80
    networks:
      - jaisocx
    environment:
      PHP_FPM_HOST: "php:9000"
      JAVA_XMS: "2g"
      JAVA_XMX: "2g"
  #      php hostname like php service name="php", port from docker/php/conf/php-fpm.d/www.conf "listen" directive (listen = 127.0.0.1:9000)

networks:
  jaisocx:
    driver: bridge

