services:
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: "Europe/Zurich"
    volumes:
      - ./laravel/:/var/www/laravel/
      - ./docker/php/logs/:/laravel-logs/
    networks:
      - jaisocx-laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  jaisocx_http:
    build:
      context: ./docker/jaisocx-http
    volumes:
      - ./docker/jaisocx-http/conf/:/usr/lib/jaisocx-http/apps/congratulations/conf/
      - ./docker/jaisocx-http/etc/:/usr/lib/jaisocx-http/etc/
      - ./docker/jaisocx-http/ssl/:/usr/lib/jaisocx-http/ssl/
      - ./docker/jaisocx-http/logs/:/usr/lib/jaisocx-http/logs/
      - ./laravel/:/var/www/laravel/
    depends_on:
      - php
    ports:
      - 443:443
      - 80:80
    networks:
      - jaisocx-laravel
    environment:
      PHP_FPM_HOST: "php:9000"
      JAVA_XMS: "2g"
      JAVA_XMX: "2g"
  #      php hostname like php service name="php", port from docker/php/conf/php-fpm.d/www.conf "listen" directive (listen = 127.0.0.1:9000)

networks:
  jaisocx-laravel:
    driver: bridge

